[package]
name = "dirscomp"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5"
walkdir = "2.5"
jwalk = "0.5"